info:
  description: pootime api 명세서
  title: Pooptime API
  version: 1.0.0
openapi: 3.0.0
paths:
  /check:
    get:
      description: 세션이 유효하면 로그인된 사용자 정보를 반환합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                  user:
                    properties:
                      id:
                        type: integer
                      user_email:
                        type: string
                      user_nick:
                        type: string
                    type: object
                type: object
          description: 로그인된 사용자 정보 반환
        '401':
          content:
            application/json:
              schema:
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: 로그인되어 있지 않음
      summary: 로그인 세션 확인
  /comments/{board_id}:
    get:
      description: 게시글 ID에 해당하는 모든 댓글을 가져옵니다.
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    content:
                      type: string
                    date:
                      format: date-time
                      type: string
                    id:
                      type: integer
                    user_id:
                      type: string
                    user_nick:
                      type: string
                  type: object
                type: array
          description: 댓글 목록 반환
      summary: 게시글에 달린 댓글 조회
  /commonsense:
    get:
      description: 상식 퀴즈 문제를 랜덤으로 반환합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  answer:
                    type: string
                  question:
                    type: string
                type: object
          description: 퀴즈 문제 반환
      summary: 상식 퀴즈 조회
  /community:
    get:
      description: 모든 게시판 글을 조회합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    board_id:
                      type: integer
                    content:
                      type: string
                    date:
                      format: date-time
                      type: string
                    title:
                      type: string
                    writer:
                      type: string
                  type: object
                type: array
          description: 게시판 글 목록 반환
      summary: 게시판 목록 조회
  /emailcheck:
    post:
      description: 입력된 이메일이 중복되는지 확인합니다.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_email:
                  format: email
                  type: string
              required:
              - user_email
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  exists:
                    type: boolean
                type: object
          description: 중복 여부 반환
      summary: 이메일 중복 확인
  /funny:
    get:
      description: 유머 게시판의 모든 게시글을 조회합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    content:
                      type: string
                    date:
                      format: date-time
                      type: string
                    id:
                      type: integer
                    title:
                      type: string
                    writer:
                      type: string
                  type: object
                type: array
          description: 게시글 목록 반환
      summary: 유머 게시글 조회
  /horror:
    get:
      description: 공포 게시판의 모든 게시글을 조회합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    content:
                      type: string
                    date:
                      format: date-time
                      type: string
                    id:
                      type: integer
                    title:
                      type: string
                    writer:
                      type: string
                  type: object
                type: array
          description: 공포 게시글 목록
      summary: 공포 게시글 조회
  /like/{board_id}:
    post:
      description: 특정 게시글에 사용자가 추천(좋아요)을 누릅니다.
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: integer
              required:
              - user_id
              type: object
        required: true
      responses:
        '200':
          description: 추천 성공
        '400':
          description: 잘못된 요청 또는 중복 추천
      summary: 게시글에 추천 누르기
  /login:
    get:
      description: 모든 사용자 ID와 비밀번호를 반환합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    password:
                      type: string
                    user_id:
                      type: string
                  type: object
                type: array
          description: 사용자 목록
      summary: 모든 사용자 로그인 정보 조회
  /login/{user_id}:
    get:
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  password:
                    type: string
                  user_id:
                    type: string
                type: object
          description: 사용자 ID에 해당하는 로그인 정보
      summary: 특정 사용자 로그인 정보 조회
  /quiz:
    get:
      description: 랜덤으로 퀴즈 문제를 한 개 제공합니다.
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  answer:
                    type: string
                  id:
                    type: integer
                  question:
                    type: string
                type: object
          description: 퀴즈 문제 반환
      summary: 퀴즈 문제 조회
  /quiz/submit:
    post:
      description: 사용자가 푼 퀴즈 결과를 저장합니다.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                score:
                  type: integer
                user_id:
                  type: string
              required:
              - user_id
              - score
              type: object
        required: true
      responses:
        '200':
          description: 저장 완료
      summary: 퀴즈 결과 저장
  /register:
    post:
      description: 새로운 사용자를 등록합니다.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_email:
                  type: string
                user_id:
                  type: string
                user_nick:
                  type: string
                user_pw:
                  type: string
              required:
              - user_id
              - user_pw
              - user_nick
              - user_email
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                type: object
          description: 회원가입 성공
        '400':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                type: object
          description: 입력 오류 또는 중복 사용자
      summary: 회원 가입
